<?php

/**
 * @file
 * Provides miscellaneous functionality
 * 
 */

/**
 * Implementation of hook_menu().
 */
function angulars_menu() {
  return array(
    'angulars' => array(
      'title' => t('AngularJS Example'),
      'route_name' => 'angulars',
    ),
  );
}

/**
 * Implements hooK_preprocess_html().
 */
function angulars_preprocess_html(&$variables) {
  $variables['attributes']['ng-app'] = "myApp";
}